# Default values for keepalived-cloud-provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jkwong/keepalived-cloud-provider
  tag: latest
  pullPolicy: IfNotPresent

rbac:
  enabled: true
  icp: true

cloudProvider:
  service:
    cidr: 10.250.0.0/24
    reserved: 10.250.0.1

keepAlived:
    
